import {
  Sparkles,
  UserCircle,
  Building2,
  Calendar,
  ClipboardList,
  Gamepad2,
  BookOpen,
  Share2,
  FileText,
  Lightbulb,
  Store,
  Users,
  Image,
  MousePointerClick,
  PartyPopper,
  Mail,
  PenTool,
  Megaphone,
  DollarSign,
  ClipboardCheck,
  GitBranch,
  Video,
  Send,
  Layout,
  HelpCircle,
  ListOrdered,
  MessageCircle,
  BarChart3,
  Search,
  ShoppingBag,
  Tv,
  Globe,
  Brain,
  Star,
  Bot,
  LucideIcon,
} from 'lucide-react';

export type ToolCategory = 'page' | 'quiz' | 'writing' | 'marketing' | 'monetization';

export type ToolCategoryDef = {
  id: ToolCategory;
  label: string;
  icon: LucideIcon;
};

export const TOOL_CATEGORIES: ToolCategoryDef[] = [
  { id: 'page', label: 'LP・ページ作成', icon: Layout },
  { id: 'quiz', label: '診断・クイズ', icon: HelpCircle },
  { id: 'writing', label: 'ライティング・制作', icon: PenTool },
  { id: 'marketing', label: '集客・イベント', icon: Megaphone },
  { id: 'monetization', label: '収益化・販売', icon: DollarSign },
];

export type ToolItem = {
  id: string;
  label: string;
  icon: LucideIcon;
  description: string;
  color: { bg: string; text: string; border: string };
  href?: string;
  category: ToolCategory;
};

export const TOOL_ITEMS: ToolItem[] = [
  // LP・ページ作成
  {
    id: 'profile',
    label: 'プロフィールメーカー',
    icon: UserCircle,
    description: 'プロフィールLP',
    color: { bg: 'bg-indigo-50', text: 'text-indigo-600', border: 'border-indigo-200' },
    href: '/profile/editor',
    category: 'page',
  },
  {
    id: 'business',
    label: 'LPメーカー',
    icon: Building2,
    description: 'ビジネスLP作成',
    color: { bg: 'bg-indigo-50', text: 'text-indigo-600', border: 'border-indigo-200' },
    href: '/business/editor',
    category: 'page',
  },
  {
    id: 'webinar',
    label: 'ウェビナーLPメーカー',
    icon: Video,
    description: 'ウェビナーLP作成',
    color: { bg: 'bg-indigo-50', text: 'text-indigo-600', border: 'border-indigo-200' },
    href: '/webinar/editor',
    category: 'page',
  },
  {
    id: 'onboarding',
    label: 'ガイドメーカー',
    icon: MousePointerClick,
    description: 'ガイド作成',
    color: { bg: 'bg-indigo-50', text: 'text-indigo-600', border: 'border-indigo-200' },
    href: '/onboarding/editor',
    category: 'page',
  },
  {
    id: 'site',
    label: 'ホームページメーカー',
    icon: Globe,
    description: '複数ページサイト作成',
    color: { bg: 'bg-cyan-50', text: 'text-cyan-600', border: 'border-cyan-200' },
    href: '/site/editor',
    category: 'page',
  },

  // 診断・クイズ
  {
    id: 'quiz',
    label: '診断クイズメーカー',
    icon: Sparkles,
    description: '診断クイズ作成',
    color: { bg: 'bg-emerald-50', text: 'text-emerald-600', border: 'border-emerald-200' },
    href: '/quiz/editor',
    category: 'quiz',
  },
  {
    id: 'bigfive',
    label: 'Big Five性格診断',
    icon: Brain,
    description: '科学的性格診断',
    color: { bg: 'bg-violet-50', text: 'text-violet-600', border: 'border-violet-200' },
    href: '/bigfive',
    category: 'quiz',
  },
  {
    id: 'entertainment',
    label: 'エンタメ診断メーカー',
    icon: PartyPopper,
    description: 'エンタメ診断作成',
    color: { bg: 'bg-emerald-50', text: 'text-emerald-600', border: 'border-emerald-200' },
    href: '/entertainment/create',
    category: 'quiz',
  },
  {
    id: 'fortune',
    label: '生年月日占い',
    icon: Star,
    description: '九星気学・数秘術・四柱推命',
    color: { bg: 'bg-indigo-50', text: 'text-indigo-600', border: 'border-indigo-200' },
    href: '/fortune',
    category: 'quiz',
  },

  // ライティング・制作
  {
    id: 'salesletter',
    label: 'セールスライター',
    icon: FileText,
    description: 'セールスレター',
    color: { bg: 'bg-amber-50', text: 'text-amber-600', border: 'border-amber-200' },
    href: '/salesletter/editor',
    category: 'writing',
  },
  {
    id: 'thumbnail',
    label: 'サムネイルメーカー',
    icon: Image,
    description: 'AIサムネイル作成',
    color: { bg: 'bg-amber-50', text: 'text-amber-600', border: 'border-amber-200' },
    href: '/thumbnail/editor',
    category: 'writing',
  },
  {
    id: 'sns-post',
    label: 'SNS投稿メーカー',
    icon: Send,
    description: 'SNS投稿作成',
    color: { bg: 'bg-amber-50', text: 'text-amber-600', border: 'border-amber-200' },
    href: '/sns-post/editor',
    category: 'writing',
  },
  {
    id: 'kindle',
    label: 'Kindle出版メーカー',
    icon: BookOpen,
    description: 'AI書籍執筆',
    color: { bg: 'bg-amber-50', text: 'text-amber-600', border: 'border-amber-200' },
    href: '/kindle',
    category: 'writing',
  },
  {
    id: 'kindle-discovery',
    label: 'ネタ発掘診断',
    icon: Lightbulb,
    description: '執筆ネタ発掘',
    color: { bg: 'bg-amber-50', text: 'text-amber-600', border: 'border-amber-200' },
    href: '/kindle/discovery',
    category: 'writing',
  },

  // 集客・イベント
  {
    id: 'booking',
    label: '予約メーカー',
    icon: Calendar,
    description: '予約ページ作成',
    color: { bg: 'bg-cyan-50', text: 'text-cyan-600', border: 'border-cyan-200' },
    href: '/booking/new',
    category: 'marketing',
  },
  {
    id: 'attendance',
    label: '出欠メーカー',
    icon: Users,
    description: '出欠管理',
    color: { bg: 'bg-cyan-50', text: 'text-cyan-600', border: 'border-cyan-200' },
    href: '/attendance/editor',
    category: 'marketing',
  },
  {
    id: 'survey',
    label: 'アンケートメーカー',
    icon: ClipboardList,
    description: 'アンケート作成',
    color: { bg: 'bg-cyan-50', text: 'text-cyan-600', border: 'border-cyan-200' },
    href: '/survey/editor',
    category: 'marketing',
  },
  {
    id: 'newsletter',
    label: 'メルマガメーカー',
    icon: Mail,
    description: 'メルマガ配信',
    color: { bg: 'bg-cyan-50', text: 'text-cyan-600', border: 'border-cyan-200' },
    href: '/newsletter/campaigns/new',
    category: 'marketing',
  },
  {
    id: 'step-email',
    label: 'ステップメールメーカー',
    icon: ListOrdered,
    description: 'ステップメール自動配信',
    color: { bg: 'bg-cyan-50', text: 'text-cyan-600', border: 'border-cyan-200' },
    href: '/step-email/sequences/new',
    category: 'marketing',
  },
  {
    id: 'funnel',
    label: 'ファネルメーカー',
    icon: GitBranch,
    description: 'ファネル構築',
    color: { bg: 'bg-cyan-50', text: 'text-cyan-600', border: 'border-cyan-200' },
    href: '/funnel/new',
    category: 'marketing',
  },
  {
    id: 'line',
    label: 'LINE公式連携',
    icon: MessageCircle,
    description: 'LINE公式アカウント連携・配信',
    color: { bg: 'bg-green-50', text: 'text-green-600', border: 'border-green-200' },
    category: 'marketing',
  },
  {
    id: 'youtube-analysis',
    label: 'YouTube競合分析',
    icon: BarChart3,
    description: 'YouTube動画の統計分析',
    color: { bg: 'bg-cyan-50', text: 'text-cyan-600', border: 'border-cyan-200' },
    href: '/youtube-analysis/editor',
    category: 'marketing',
  },
  {
    id: 'youtube-keyword-research',
    label: 'YouTubeキーワードリサーチ',
    icon: Search,
    description: 'YouTube検索キーワード分析',
    color: { bg: 'bg-cyan-50', text: 'text-cyan-600', border: 'border-cyan-200' },
    href: '/youtube-keyword-research/editor',
    category: 'marketing',
  },
  {
    id: 'kindle-keywords',
    label: 'Kindleキーワードリサーチ',
    icon: BookOpen,
    description: 'Kindle出版キーワード分析',
    color: { bg: 'bg-orange-50', text: 'text-orange-600', border: 'border-orange-200' },
    href: '/kindle-keywords/editor',
    category: 'writing',
  },
  {
    id: 'google-keyword-research',
    label: 'Googleキーワードリサーチ',
    icon: Search,
    description: 'Google検索キーワード競合分析',
    color: { bg: 'bg-teal-50', text: 'text-teal-600', border: 'border-teal-200' },
    href: '/google-keyword-research/editor',
    category: 'marketing',
  },
  {
    id: 'rakuten-research',
    label: '楽天市場リサーチ',
    icon: ShoppingBag,
    description: '楽天商品キーワード分析',
    color: { bg: 'bg-rose-50', text: 'text-rose-600', border: 'border-rose-200' },
    href: '/rakuten-research/editor',
    category: 'marketing',
  },
  {
    id: 'niconico-keyword-research',
    label: 'ニコニコリサーチ',
    icon: Tv,
    description: 'ニコニコ動画キーワード分析',
    color: { bg: 'bg-orange-50', text: 'text-orange-600', border: 'border-orange-200' },
    href: '/niconico-keyword-research/editor',
    category: 'marketing',
  },
  {
    id: 'reddit-keyword-research',
    label: 'Redditリサーチ',
    icon: Globe,
    description: 'Reddit投稿キーワード分析',
    color: { bg: 'bg-orange-50', text: 'text-orange-600', border: 'border-orange-200' },
    href: '/reddit-keyword-research/editor',
    category: 'marketing',
  },

  // 収益化・販売
  {
    id: 'order-form',
    label: 'フォームメーカー',
    icon: ClipboardCheck,
    description: '申し込み・決済フォーム',
    color: { bg: 'bg-purple-50', text: 'text-purple-600', border: 'border-purple-200' },
    href: '/order-form/new',
    category: 'page',
  },
  {
    id: 'my-games',
    label: 'ゲーミフィケーション',
    icon: Gamepad2,
    description: 'ゲーム作成',
    color: { bg: 'bg-purple-50', text: 'text-purple-600', border: 'border-purple-200' },
    href: '/gamification',
    category: 'monetization',
  },
  {
    id: 'marketplace-seller',
    label: 'スキルマーケット',
    icon: Store,
    description: 'スキル出品管理',
    color: { bg: 'bg-purple-50', text: 'text-purple-600', border: 'border-purple-200' },
    href: '/marketplace/seller',
    category: 'monetization',
  },
  {
    id: 'affiliate',
    label: 'アフィリエイト',
    icon: Share2,
    description: '紹介プログラム',
    color: { bg: 'bg-purple-50', text: 'text-purple-600', border: 'border-purple-200' },
    href: '/affiliate',
    category: 'monetization',
  },
];
