import {
  Layout, Sparkles, Edit3, Trophy, Share2, Lock,
  MessageSquare, Palette, Eye, Star, Heart, Zap,
  Shield, Globe, Users, Settings, Bell, BookOpen,
  Code, Coffee, Gift, Home, Info, Key, Mail,
  Map, Phone, Search, Target, ThumbsUp, Wand2,
  Clock, Camera, FileText, Folder, HelpCircle,
  Lightbulb, Monitor, Rocket, ShoppingCart, Tag,
  Upload, Video, Headphones, Compass, Award,
  BarChart3, CheckCircle, Layers, MousePointer,
} from 'lucide-react';
import React from 'react';

export const ICON_MAP: Record<string, React.ElementType> = {
  Layout, Sparkles, Edit3, Trophy, Share2, Lock,
  MessageSquare, Palette, Eye, Star, Heart, Zap,
  Shield, Globe, Users, Settings, Bell, BookOpen,
  Code, Coffee, Gift, Home, Info, Key, Mail,
  Map, Phone, Search, Target, ThumbsUp, Wand2,
  Clock, Camera, FileText, Folder, HelpCircle,
  Lightbulb, Monitor, Rocket, ShoppingCart, Tag,
  Upload, Video, Headphones, Compass, Award,
  BarChart3, CheckCircle, Layers, MousePointer,
};

export const ICON_NAMES = Object.keys(ICON_MAP);

// アイコン名の日本語ラベル（検索用）
export const ICON_LABELS: Record<string, string> = {
  Layout: 'レイアウト',
  Sparkles: 'キラキラ',
  Edit3: '編集',
  Trophy: 'トロフィー',
  Share2: '共有',
  Lock: 'ロック',
  MessageSquare: 'メッセージ',
  Palette: 'パレット',
  Eye: '目・閲覧',
  Star: '星',
  Heart: 'ハート',
  Zap: '稲妻',
  Shield: 'シールド',
  Globe: '地球',
  Users: 'ユーザー',
  Settings: '設定',
  Bell: 'ベル',
  BookOpen: '本',
  Code: 'コード',
  Coffee: 'コーヒー',
  Gift: 'ギフト',
  Home: 'ホーム',
  Info: '情報',
  Key: '鍵',
  Mail: 'メール',
  Map: '地図',
  Phone: '電話',
  Search: '検索',
  Target: 'ターゲット',
  ThumbsUp: 'いいね',
  Wand2: '魔法',
  Clock: '時計',
  Camera: 'カメラ',
  FileText: 'ファイル',
  Folder: 'フォルダ',
  HelpCircle: 'ヘルプ',
  Lightbulb: '電球・アイデア',
  Monitor: 'モニター',
  Rocket: 'ロケット',
  ShoppingCart: 'カート',
  Tag: 'タグ',
  Upload: 'アップロード',
  Video: 'ビデオ',
  Headphones: 'ヘッドフォン',
  Compass: 'コンパス',
  Award: '賞',
  BarChart3: 'グラフ',
  CheckCircle: 'チェック',
  Layers: 'レイヤー',
  MousePointer: 'マウス',
};
